//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.29 at 10:04:02 PM CDT 
//


package com.ryan.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ryan.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ryan.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot }
     * 
     */
    public com.ryan.jaxb.BillRoot createBill() {
        return new com.ryan.jaxb.BillRoot();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Subjects }
     * 
     */
    public com.ryan.jaxb.BillRoot.Subjects createBillSubjects() {
        return new com.ryan.jaxb.BillRoot.Subjects();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Relatedbills }
     * 
     */
    public com.ryan.jaxb.BillRoot.Relatedbills createBillRelatedbills() {
        return new com.ryan.jaxb.BillRoot.Relatedbills();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Committees }
     * 
     */
    public com.ryan.jaxb.BillRoot.Committees createBillCommittees() {
        return new com.ryan.jaxb.BillRoot.Committees();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Actions }
     * 
     */
    public com.ryan.jaxb.BillRoot.Actions createBillActions() {
        return new com.ryan.jaxb.BillRoot.Actions();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Actions.Action }
     * 
     */
    public com.ryan.jaxb.BillRoot.Actions.Action createBillActionsAction() {
        return new com.ryan.jaxb.BillRoot.Actions.Action();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Cosponsors }
     * 
     */
    public com.ryan.jaxb.BillRoot.Cosponsors createBillCosponsors() {
        return new com.ryan.jaxb.BillRoot.Cosponsors();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Titles }
     * 
     */
    public com.ryan.jaxb.BillRoot.Titles createBillTitles() {
        return new com.ryan.jaxb.BillRoot.Titles();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Status }
     * 
     */
    public com.ryan.jaxb.BillRoot.Status createBillStatus() {
        return new com.ryan.jaxb.BillRoot.Status();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.State }
     * 
     */
    public com.ryan.jaxb.BillRoot.State createBillState() {
        return new com.ryan.jaxb.BillRoot.State();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Introduced }
     * 
     */
    public com.ryan.jaxb.BillRoot.Introduced createBillIntroduced() {
        return new com.ryan.jaxb.BillRoot.Introduced();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Sponsor }
     * 
     */
    public com.ryan.jaxb.BillRoot.Sponsor createBillSponsor() {
        return new com.ryan.jaxb.BillRoot.Sponsor();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Subjects.Term }
     * 
     */
    public com.ryan.jaxb.BillRoot.Subjects.Term createBillSubjectsTerm() {
        return new com.ryan.jaxb.BillRoot.Subjects.Term();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Relatedbills.Bill }
     * 
     */
    public com.ryan.jaxb.BillRoot.Relatedbills.Bill createBillRelatedbillsBill() {
        return new com.ryan.jaxb.BillRoot.Relatedbills.Bill();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Committees.Committee }
     * 
     */
    public com.ryan.jaxb.BillRoot.Committees.Committee createBillCommitteesCommittee() {
        return new com.ryan.jaxb.BillRoot.Committees.Committee();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Actions.Action.Reference }
     * 
     */
    public com.ryan.jaxb.BillRoot.Actions.Action.Reference createBillActionsActionReference() {
        return new com.ryan.jaxb.BillRoot.Actions.Action.Reference();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Cosponsors.Cosponsor }
     * 
     */
    public com.ryan.jaxb.BillRoot.Cosponsors.Cosponsor createBillCosponsorsCosponsor() {
        return new com.ryan.jaxb.BillRoot.Cosponsors.Cosponsor();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Titles.Title }
     * 
     */
    public com.ryan.jaxb.BillRoot.Titles.Title createBillTitlesTitle() {
        return new com.ryan.jaxb.BillRoot.Titles.Title();
    }

    /**
     * Create an instance of {@link com.ryan.jaxb.BillRoot.Status.Introduced }
     * 
     */
    public com.ryan.jaxb.BillRoot.Status.Introduced createBillStatusIntroduced() {
        return new com.ryan.jaxb.BillRoot.Status.Introduced();
    }

}
